# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'navigatAR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for navigatAR
  pod 'CodableFirebase'
  pod 'Eureka'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'IndoorAtlas'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

end
