# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'navigatAR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for navigatAR
  pod 'CodableFirebase'
  pod 'Eureka'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'IndoorAtlas'
  pod 'FuzzyMatchingSwift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

end
