# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'navigatAR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for navigatAR
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Eureka'

end
